import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Yellow Box",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f4d04e] h-screen grid grid-cols-1 grid-rows-1 justify-items-center items-center">
        {children}
      </body>
    </html>
  );
}
